### ISSUE TITLE
select all up or all down

### ISSUE THREAD

**Issue by b8e5n** [raulhaag/MiMangaNu#183] opened 2015-12-11 10:35 UTC
When I started to use the app, I wanted to mark all the chapters I red from a manga, but I had only the choice of selecting all of the 600 chapters, or one by one... I did my 200 clicks...
Anyway, just to say, it could be nice to select a chapter and then have the option to select all the previous or following chapter.

**Comment by Dostoi** [comment] 2015-12-11 11:10
Duplicate of #178

**Comment by raulhaag** [comment] 2015-12-27 14:41
![added](https://cloud.githubusercontent.com/assets/2048339/12010659/bed0b098-ac8e-11e5-99a8-03241112fb95.jpg)
ready for next version

**Closed by raulhaag** 2015-12-27 14:41 UTC
