### ISSUE TITLE
Mangahere not working

### ISSUE THREAD

**Issue by GyanPreet** [raulhaag/MiMangaNu#488] opened 2017-11-21 21:38 UTC
Mangahere hasnt been working for two weeks
It doesnt download it just says couldnt load page count.
Plz fix, i hate to fall behind.
Thank you in advance, for all your hard work fpr leeping this app updated and running.
Dev. You are the best

**Comment by tempura-san** [comment] 2017-11-26 06:16
This is a duplicate of #481 and should already be resolved for 1.74.
Please check again once the new release is out.

**Closed** 2017-12-08 20:25 UTC
