### ISSUE TITLE
Kissmanga not working

### ISSUE THREAD

**Issue by sm7297** [raulhaag/MiMangaNu#144] opened 2015-11-02 10:05 UTC
1.38 and also can you provide steps on how can i add other website to the application i have installed android studio but cant able to understand

**Comment by Dostoi** [comment] 2015-11-02 11:09
With which version of the app ?

**Comment by Blapple** [comment] 2015-11-02 13:18
Kissmanga is also not working for me on version 1.37 and 1.38, haven't tried any other versions.

**Comment by Dostoi** [comment] 2015-11-02 17:42
Duplicate of #143 
Already fixed, just need to wait for the next version or compile yourself

**Comment by raulhaag** [comment] 2015-11-06 19:13
ready on 1.39

**Closed by raulhaag** 2015-11-06 19:13 UTC
