### ISSUE TITLE
Seamless transition reading reset the last chapter when reaching it in horizontal reading

### ISSUE THREAD

**Issue by Dostoi** [raulhaag/MiMangaNu#289] opened 2016-06-19 07:03 UTC
When you reach the end of the last chapter in horizontal reading and with the seamless transition reading, a popup appears asking if you want to delete or not the chapter and then leave the chapter and reset it to the start marking it as unread and doesn't delete the pictures of the chapter

With the last travis

**Comment by xtj-9182** [comment] 2016-06-20 18:36
what is horizontal reading ? Is it the lock to landscape mode ?

I'm trying but I can't reproduce this, can you elaborate more clearly ?

**Comment by Dostoi** [comment] 2016-06-20 19:27
With the continous reader, when reading from right to left. You have to enable the seamless chapter transition
If you're reading the last available chapter of a manga and you reach the end of it but still try to swipe for a next page, the reader is closed after asking if we want to delete it, and the chapter is reset without deleting the picture.

Don't know if it's clearer ^^

**Comment by xtj-9182** [comment] 2016-06-20 19:39
I think I understand it better now but I still can't reproduce it.
I'm in continuous reader and in Right to left direction,
when I go to the last chapter I get the pop up saying it's the last chapter
when I check the delete images checkbox and click on close I'm back in  the MangaFragment and
the Images are deleted and the status of the chapter is read. I tried with a Manga and a Manhwa.

Is there any specific Manga where this is happening ?

**Comment by Dostoi** [comment] 2016-06-20 20:04
The debug crashes on start ^^

Ut happens with this manga from this server http://kissmanga.com/Manga/Yamikin-Ushijima-kun

And I noticed that if instead of pressing close I press cancel, the reader is set to the previous chapter instead of staying on the same chapter

**Comment by raulhaag** [comment] 2016-06-20 21:50
got it, in last chapter (any manga) at end it say this is the lasdt chapter.... and if you select delete images it doesn't work,

**Comment by raulhaag** [comment] 2016-06-20 22:45
test last commit

**Comment by raulhaag** [comment] 2016-06-20 23:00
![stwe](https://cloud.githubusercontent.com/assets/2048339/16212897/76cab032-3721-11e6-8584-855ea5f9a74c.jpg)
@xtj-9182 about seamless transition not working like the image any problem if i mod it?

**Comment by Dostoi** [comment] 2016-06-21 06:45
It's good now

**Comment by xtj-9182** [comment] 2016-06-21 13:47
@raulhaag yeah go ahead. Sometimes I don't understand every part of the code yet and that was something that I couldn't figure out yet.

**Comment by raulhaag** [comment] 2016-06-21 17:34
@xtj-9182 in one word hierarchy, it has valid method for l2r and r2l, resolving bad hierarchy l2r extending r2l.

**Comment by xtj-9182** [comment] 2016-06-22 15:07
yeah that makes sense, at some point I was wondering why l2r would extend r2l but I didn't think too deep about that. Anyway I think this Issue can be closed now.

**Closed** 2016-06-27 19:10 UTC
