### ISSUE TITLE
French catalogue ? Japscan.com

### ISSUE THREAD

**Issue by glenntitan** [raulhaag/MiMangaNu#187] opened 2015-12-20 09:52 UTC
Hello and thank you for the tremendous work. Can you add another french catalogue like japscan.com, this is an awesome site with a lot of mangas. I'm not a developer so i cannot be very useful but tell me if i can do anything to help, your app is wonderful ! Keep the good work !

**Comment by xken2x** [comment] 2015-12-20 17:18
From i what see, The proyect owner is taking a well deserved vacations, and the app probably continue un january, and i think the same as you, he is doing a excellent work!!!

**Comment by M2ck** [comment] 2015-12-20 23:00
Duplicate of #167

**Comment by raulhaag** [comment] 2015-12-21 12:29
japscan save their images in this way 
http://cdn.japscan.com/cr-images/One%20Punch%20Man/83.4/01.jpg
if i want to add i need me make an image postprocesing work, actually not supported

**Closed by raulhaag** 2015-12-21 12:29 UTC
Labels: duplicate
