### ISSUE TITLE
Mangafox not working

### ISSUE THREAD

**Issue by lvjot95** [raulhaag/MiMangaNu#448] opened 2017-09-29 05:12 UTC
Please fix mangafox, it's the best server.
Java.lang.IllegalArgumentExeption: unexpected url.

**Comment by faan11** [comment] 2017-09-29 08:26
I had a ssl error for Mangafox and Mangahere:
https://ibb.co/fGU5Qb

**Comment by tempura-san** [comment] 2017-09-29 17:46
See the comment on #447 . Both servers seem to have a problem with their SSL configuration (you can check via DigiCert SSL check).
That is the reason why connections to these servers are rejected at the moment.
This issue is a duplicate of #445.

**Comment by lvjot95** [comment] 2017-09-29 20:40
Mangafox and mangahere are already working on app mangazone, they have released an update today. Could you please fix mi mu manga also.

**Comment by tempura-san** [comment] 2017-09-30 08:58
The question is to **break** MiMangaNu with respect to SSL (at least partially) or to have the pages (like MangaHere) fix their SSL chains?
BTW MangaHere and Mangafox seem to work again at the moment as I can browse them in the app.

**Comment by tempura-san** [comment] 2017-09-30 09:40
Sorry - while browsing works, chapter download fails with the same error. So as long as the HTTP method is used it works, but as soon as HTTPS comes into play it fails - for reasons outlined in my first post.

**Comment by raulhaag** [comment] 2017-09-30 13:36
there is a way adding the certificates on the app, ifi can tomorrow i go to try that, only for this two pages

**Comment by raulhaag** [comment] 2017-09-30 23:56
ok seem like the fixes the issue and i added the needed changes for this two pages, i go to add new version for tomorrow

**Closed** 2017-09-30 23:58 UTC

**Comment by lvjot95** [comment] 2017-10-01 04:49
Thanks a lot
